Init template
VilnaCRM-Org/php-service-template pull request #1
Opened 2022-10-27 19:58 UTC by Mihailmihail111

2022-10-28 18:03 UTC, Kravalg requested changes
Also please add CI checks through Github Actions for pull requests (psalm, phpunit, behat , [symfony security check](https://symfony.com/doc/current/setup.html#checking-security-vulnerabilities), composer validate, [rips security checker](https://github.com/robocoder/rips-scanner), [sonar security checker](https://github.com/SonarSource/sonar-php))

Also add changelog generation and publish the first version v1.0.0 of this repository

2022-10-31 19:58 UTC, vilnacrm commented
add @Kravalg and @Mihailmihail111 to codeowners
https://stackoverflow.com/questions/46340474/set-a-default-reviewer

2023-02-08 20:31 UTC, Kravalg commented on README.md
> -# php-service-template
fixed

2023-02-10 22:43 UTC, Kravalg commented
the wrong pr

2023-02-10 22:43 UTC, closed without merging