fix(#21): try to add github workflows and update MAKEFILE
VilnaCRM-Org/php-service-template pull request #22
Opened 2024-07-11 14:43 UTC by Derane

## Description
try to add github workflows and update MAKEFILE

## Related Issue

https://github.com/VilnaCRM-Org/php-service-template/issues/21

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/php-service-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] You have only one commit (if not, squash them into one commit).

2024-07-11 21:53 UTC, Kravalg requested changes

2024-07-11 21:53 UTC, Kravalg commented on .github/workflows/deptrac.yml
> +          php-version: '8.2'
It will be better to use the GitHub environment variable
We have the php version already for this purpose, it’s name is `PHP_VERSION`
Please change it in all of the github actions

2024-07-11 21:53 UTC, Kravalg commented on .github/workflows/deptrac.yml
> +        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
It will be better to use the `make install` in all of the github actions

2024-07-11 21:53 UTC, Kravalg commented on .github/workflows/graphql-diff.yml
> +        run: composer require symfony/runtime
Please remove this step, we should avoid using the composer required inside the GitHub actions
It will be better to commit the Symfony/runtime to composer.json and composer.lock instead

2024-07-11 21:53 UTC, Kravalg commented on deptrac.yaml
> +parameters:
It will be better to move the deptrac config from the user service 
https://github.com/VilnaCRM-Org/user-service/blob/main/deptrac.yaml

2024-07-12 18:02 UTC, Derane commented on .github/workflows/deptrac.yml
> +        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
We have to use make start before `make install`
Because if we look at MAKEFILE:
```
@$(COMPOSER) install --no-progress --prefer-dist --optimize-autoloader
	COMPOSER = $(EXEC_PHP) composer
```

2024-07-12 18:05 UTC, Derane commented on .github/workflows/graphql-diff.yml
> +        run: composer require symfony/runtime
I replace this "composer install", if we try to do `make install` we will receive such problem: 
https://github.com/VilnaCRM-Org/php-service-template/actions/runs/9905997156/job/27366692569

2024-07-14 11:09 UTC, Kravalg commented on .github/workflows/deptrac.yml
> +        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
1. We need to move Makefile from the user service to the php service template
2. We need to refactor Makefile to use `CI=1 make infection` instead of `make ci-infection`

2024-07-14 16:17 UTC, Kravalg commented on .github/workflows/graphql-diff.yml
> +        run: composer require symfony/runtime
So install symfony/runtime locally and then commit and push new composer.json and composer.lock to avoid such bicycles

2024-07-17 22:03 UTC, Kravalg requested changes
We need to fix the CI and resolve all comments

2024-07-20 22:38 UTC, Kravalg requested changes
Looks good, please fix the merge conflicts and we will merge this PR

2024-07-22 22:45 UTC, merged