move infection and structurizr in docker
VilnaCRM-Org/php-service-template pull request #27
Opened 2024-07-19 13:16 UTC by Derane

## Description
move infection and structurizr in docker

## Related Issue

https://github.com/VilnaCRM-Org/php-service-template/issues/26

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/php-service-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] You have only one commit (if not, squash them into one commit).

2024-07-20 22:25 UTC, Kravalg commented on composer.json
> +        "infection/infection": "^0.27.10",
It will be better to write the latest version 0.29

2024-07-20 22:26 UTC, Kravalg commented on .env
> +STRUCTURIZR_PORT=
It will be better to write the default port there

2024-07-20 22:27 UTC, Kravalg commented on infection.json5
> +    ],
It will be better to remove this, because we removed the DataFixtures from the src directory

2024-07-20 22:27 UTC, Kravalg requested changes
Good job, I left several comments

2024-07-22 22:43 UTC, Kravalg approved these changes
Looks good, please fix the conflicts and then we will be able to merge the PR

2024-07-23 22:49 UTC, Kravalg requested changes
Let's fix the CI and we will be able to merge this PR

2024-07-25 08:23 UTC, Derane commented
> Let's fix the CI and we will be able to merge this PR

I configured mutations in 'move shared' pull request, because here we have no tests

2024-07-25 21:33 UTC, Kravalg approved these changes

2024-07-25 21:34 UTC, merged