fix(#28): move shared from user-service
VilnaCRM-Org/php-service-template pull request #29
Opened 2024-07-19 17:56 UTC by Derane

## Description
move shared from user-service

## Related Issue

https://github.com/VilnaCRM-Org/php-service-template/issues/28

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/php-service-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] You have only one commit (if not, squash them into one commit).

2024-07-19 18:01 UTC, Derane commented
For this PR, I am reduced complexity to 88%, I think after I found issue why this happening we can move back complexity

2024-07-19 23:37 UTC, Kravalg commented
@Derane 

https://sonarcloud.io/component_measures?metric=new_duplicated_lines_density&selected=VilnaCRM-Org_php-service-template%3Atests%2FUnit%2FShared%2FApplication%2FOpenApi%2FBuilder&pullRequest=29&id=VilnaCRM-Org_php-service-template

![IMG_4996](https://github.com/user-attachments/assets/522bf58e-65a6-4404-90a1-3b25eb3da34a)

2024-07-20 00:50 UTC, Kravalg requested changes
Awesome job 

I think we need to change all `example` code for the health check endpoint functionality and remove unnecessary classes

2024-07-20 00:50 UTC, Kravalg commented on .env
> +MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
We have localstack for this purpose in the docker-compose.yaml
It will be better to use message broker for the messenger instead of database that is not suited for such functionality

2024-07-20 00:50 UTC, Kravalg commented on .php-cs-fixer.dist.php
> -        '@Symfony' => true,
It will be better to return Symfony rules for the code style

2024-07-20 00:50 UTC, Kravalg commented on composer.json
> +        "dg/bypass-finals": "^1.5",
It is better to use this library in the require-dev section, as this package is only used in tests

2024-07-20 00:50 UTC, Kravalg commented on composer.json
> +        "fakerphp/faker": "^1.23.0",
It is better to use this library in the require-dev section, as this package is only used in tests

2024-07-20 00:50 UTC, Kravalg commented on composer.json
> +        "lambdish/phunctional": "^2.1",
Why do we need it ?

2024-07-20 00:50 UTC, Kravalg commented on config/packages/messenger.yaml
> +        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
It will be better to remove the comments

2024-07-20 00:50 UTC, Kravalg commented on config/packages/messenger.yaml
> +            # https://symfony.com/doc/current/messenger.html#transport-configuration
I propose to configure the localstack aws sqs

2024-07-20 00:50 UTC, Kravalg commented on config/packages/messenger.yaml
> +# when@test:
It will be better there to uncomment this part with in memory option

2024-07-20 00:50 UTC, Kravalg commented on src/Shared/Application/OpenApi/Builder/ArrayContextBuilder.php
> +            'application/json' => [
Why do we need example?
We can use doc for healthcheck

2024-07-20 00:50 UTC, Kravalg commented on src/Shared/Application/OpenApi/Builder/ContextBuilder.php
> +                'example' => '',
It will be better to avoid using the example

2024-07-20 00:50 UTC, Kravalg commented on tests/bootstrap.php
> +BypassFinals::enable();
It will be better to move this to the end of file

2024-07-22 20:55 UTC, Derane commented on composer.json
> +        "lambdish/phunctional": "^2.1",
We need it for tests I move it in require-dev

2024-07-22 20:57 UTC, Derane commented on .php-cs-fixer.dist.php
> -        '@Symfony' => true,
![image](https://github.com/user-attachments/assets/b5c84ed9-981e-4728-a080-dfda11d8090e)
in this case it will make 1 line from 84-86 lines and phpinsights dont allow to commit

2024-07-22 20:58 UTC, Derane commented
I resolve some conversation, now we have 90% complexity

2024-07-22 22:54 UTC, Kravalg commented
> I resolve some conversation, now we have 90% complexity

We need to pass the SonarCloud quality gates

2024-07-23 22:51 UTC, Kravalg requested changes
It will be better to fix the issues in the SonarCloud

2024-07-25 21:35 UTC, Kravalg requested changes
Let's fix the merge conflict and we will be able to merge this PR

2024-07-28 19:33 UTC, Kravalg approved these changes

2024-07-28 19:33 UTC, merged